spring:
  application:
    name:
      hotel
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/yukgaejang?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&createDatabaseIfNotExist=true
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
jwt:
  secret: mfnbmUiFDjhuPqceBpS7eNcy8w5MBHJkVgvhvjMLnygvJBjNlbGHcVGjvHCgIDxaAsSNJvHVDxgVHcXSJBgCXRymUKFOLJvHVDxgVHcXSJDHHd
  token-validity-in-seconds: 86400
